[package]
authors = ["Cameron Eldridge <cameldridge+git@gmail.com>"]
edition = "2018"
name = "server"
version = "0.1.0"

[dependencies]
env_logger = "0.6"
log = "0.4"
warp = "0.1"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.7"
