[package]
authors = ["Cameron Eldridge <cameldridge@gmail.com>"]
edition = "2018"
name = "server"
version = "0.1.0"

[dependencies]
shared = { path = "../shared" }
data = { path = "../data" }

dotenv = "0.15"
env_logger = "0.7"
juniper = { version = "0.14", default-features = false, features = ["chrono", "uuid"] }
juniper_rocket = "0.5"
log = "0.4"
rocket = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
